[package]
name = "what-to-eat"
version = "0.1.0"
authors = ["WB20220706007 <1074059594@qq.com>"]
license = "MIT"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
crossterm = "0.27.0"
rand = "0.8.5"
ratatui = "0.26.0"
